### PR TITLE
Rustup to rustc 1.25.0-nightly (97520ccb1 2018-01-21)

### LINKED ISSUE #2388: Fails to build on rustc 1.25.0-nightly (97520ccb1 2018-01-21)
```
error[E0050]: method `late_callback` has 7 parameters but the declaration in trait `rustc_driver::CompilerCalls::late_callback` has 8
  --> src/driver.rs:66:16
   |
66 |         ofile: &Option<PathBuf>,
   |                ^^^^^^^^^^^^^^^^ expected 8 parameters, found 7
   |
   = note: `late_callback` from trait: `fn(&mut Self, &rustc_trans_utils::trans_crate::TransCrate, &getopts::Matches, &rustc::session::Session, &rustc::middle::cstore::CrateStore, &rustc::session::config::Input, &std::option::Option<std::path::PathBuf>, &std::option::Option<std::path::PathBuf>) -> rustc_driver::Compilation`
```

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #2388.

### CODE REVIEW

**Comment by Manishearth** [comment]
thanks!
