### PR TITLE
rustup

### LINKED ISSUE #2698: Clippy not working with latest nightly: 1.27.0-nightly (7f3444e1b 2018-04-26)
Various failures:

```
Compiling unreachable v1.0.0                                                                                                                                              
error[E0658]: procedural macros cannot be expanded to expressions                                                                                                            
  --> mini-macro/src/lib.rs:8:5                                                                                                                                              
   |                                                                                                                                                                         
8  | /     quote!(                                                                                                                                                           
9  | |         #[allow(unused)] fn needless_take_by_value(s: String) { println!("{}", s.len()); }                                                                            
10 | |     )                                                                                                                                                                 
   | |_____^                                                                                                                                                                 
   |                                                                                                                                                                         
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable
```

Also here: https://travis-ci.org/rust-lang-nursery/rust-clippy/builds/371894001#L591-L623

### PR DESCRIPTION
**Pull request by mati865**
Fixes #2698 

Looks like https://github.com/rust-lang-nursery/rust-clippy/pull/2673 didn't enable new lints, they should be enabled now.

### CODE REVIEW

**Comment by oli-obk** [comment]
Thanks! Let's see if my mobile publishing strategy works...
