### ISSUE TITLE
Clippy fails to build on rustc 1.21.0-nightly (df511d554 2017-08-14)

### ISSUE THREAD

**Issue by jplatte** [rust-lang-nursery/rust-clippy#1960]
Full `cargo install` output:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing clippy v0.0.151
   Compiling quote v0.3.15
   Compiling regex-syntax v0.4.1
   Compiling lazy_static v0.2.8
   Compiling unicode-normalization v0.1.5
   Compiling matches v0.1.6
   Compiling either v1.1.0
   Compiling num-traits v0.1.40
   Compiling semver-parser v0.7.0
   Compiling pulldown-cmark v0.0.15
   Compiling bitflags v0.9.1
   Compiling getopts v0.2.14
   Compiling serde v1.0.11
   Compiling itoa v0.3.1
   Compiling quine-mc_cluskey v0.2.4
   Compiling unicode-xid v0.0.4
   Compiling dtoa v0.4.1
   Compiling itertools v0.6.1
   Compiling synom v0.11.3
   Compiling semver v0.6.0
   Compiling syn v0.11.11
   Compiling serde_json v1.0.2
   Compiling toml v0.4.5
   Compiling serde_derive_internals v0.15.1
   Compiling serde_derive v1.0.11
   Compiling clippy_lints v0.0.151
   Compiling cargo_metadata v0.2.3
error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/consts.rs:288:48
    |
288 |         let def = self.tables.qpath_def(qpath, id);
    |                                                ^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/consts.rs:292:54
    |
292 |                 let substs = self.tables.node_substs(id);
    |                                                      ^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0616]: field `type_dependent_defs` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:199:23
    |
199 |     let method_call = cx.tables.type_dependent_defs[&expr.id];
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `type_dependent_defs` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:199:53
    |
199 |     let method_call = cx.tables.type_dependent_defs[&expr.id];
    |                                                     ^^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0616]: field `type_dependent_defs` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:210:23
    |
210 |     let method_call = cx.tables.type_dependent_defs[&expr.id];
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `type_dependent_defs` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:210:53
    |
210 |     let method_call = cx.tables.type_dependent_defs[&expr.id];
    |                                                     ^^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:352:32
    |
352 |     cx.tables.qpath_def(qpath, id)
    |                                ^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0616]: field `adjustments` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:659:5
    |
659 |     cx.tables.adjustments.get(&e.id).is_some()
    |     ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `adjustments` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:659:31
    |
659 |     cx.tables.adjustments.get(&e.id).is_some()
    |                               ^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/mod.rs:838:40
    |
838 |             cx.tables.qpath_def(qpath, did),
    |                                        ^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/inspector.rs:148:77
    |
148 |             println!("local variable of type {}", cx.tables.node_id_to_type(local.id));
    |                                                                             ^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0616]: field `adjustments` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/inspector.rs:164:42
    |
164 |     println!("{}adjustments: {:?}", ind, cx.tables.adjustments.get(&expr.id));
    |                                          ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `adjustments` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/utils/inspector.rs:164:68
    |
164 |     println!("{}adjustments: {:?}", ind, cx.tables.adjustments.get(&expr.id));
    |                                                                    ^^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/attrs.rs:218:54
    |
218 |                 let fun_id = tables.qpath_def(qpath, path_expr.id).def_id();
    |                                                      ^^^^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/bit_mask.rs:321:50
    |
321 |             let def = cx.tables.qpath_def(qpath, lit.id);
    |                                                  ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0063]: missing field `hir_id` in initializer of `rustc::hir::Expr`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/booleans.rs:123:25
    |
123 |                         Expr {
    |                         ^^^^ missing `hir_id`

error[E0616]: field `node_types` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/booleans.rs:414:20
    |
414 |                 if self.cx.tables.node_types[&inner.id].is_bool() {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `node_types` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/booleans.rs:414:46
    |
414 |                 if self.cx.tables.node_types[&inner.id].is_bool() {
    |                                              ^^^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/cyclomatic_complexity.rs:74:48
   |
74 |         let ret_ty = cx.tables.node_id_to_type(expr.id);
   |                                                ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/cyclomatic_complexity.rs:163:57
    |
163 |                 let ty = self.cx.tables.node_id_to_type(callee.id);
    |                                                         ^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/drop_forget_ref.rs:123:53
    |
123 |             let def_id = cx.tables.qpath_def(qpath, path.id).def_id();
    |                                                     ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/eval_order_dependence.rs:70:66
   |
70 |                             let var = cx.tables.qpath_def(qpath, lhs.id).def_id();
   |                                                                  ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/eval_order_dependence.rs:307:84
    |
307 |                     if path.segments.len() == 1 && self.cx.tables.qpath_def(qpath, expr.id).def_id() == self.var {
    |                                                                                    ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0616]: field `type_dependent_defs` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/functions.rs:190:30
    |
190 |                 let def_id = self.cx.tables.type_dependent_defs[&expr.id].def_id();
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `type_dependent_defs` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/functions.rs:190:65
    |
190 |                 let def_id = self.cx.tables.type_dependent_defs[&expr.id].def_id();
    |                                                                 ^^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/functions.rs:213:55
    |
213 |             let def = self.cx.tables.qpath_def(qpath, ptr.id);
    |                                                       ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/let_if_seq.rs:142:56
    |
142 |             self.id == self.cx.tables.qpath_def(qpath, expr.id).def_id(),
    |                                                        ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/let_if_seq.rs:165:44
    |
165 |         decl == cx.tables.qpath_def(qpath, var.id).def_id(),
    |                                            ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/lifetimes.rs:287:55
    |
287 |                 match self.cx.tables.qpath_def(qpath, ty.id) {
    |                                                       ^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0616]: field `type_dependent_defs` of struct `rustc::ty::TypeckTables` is private
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:804:30
    |
804 |                 let def_id = cx.tables.type_dependent_defs[&arg.id].def_id();
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: a method `type_dependent_defs` also exists, perhaps you wish to call it

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:804:60
    |
804 |                 let def_id = cx.tables.type_dependent_defs[&arg.id].def_id();
    |                                                            ^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `&rustc::hir::ItemLocalId`
               found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:805:52
    |
805 |                 let substs = cx.tables.node_substs(arg.id);
    |                                                    ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:1056:45
     |
1056 |             self.cx.tables.qpath_def(qpath, expr.id).def_id() == self.var,
     |                                             ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
     |
     = note: expected type `rustc::hir::HirId`
                found type `syntax::ast::NodeId`

error[E0308]: mismatched types
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:1062:57
     |
1062 |             let def = self.cx.tables.qpath_def(seqpath, seqexpr.id);
     |                                                         ^^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
     |
     = note: expected type `rustc::hir::HirId`
                found type `syntax::ast::NodeId`

error[E0308]: mismatched types
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:1088:48
     |
1088 |             if self.cx.tables.qpath_def(qpath, expr.id).def_id() == self.var {
     |                                                ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
     |
     = note: expected type `rustc::hir::HirId`
                found type `syntax::ast::NodeId`

error[E0308]: mismatched types
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/loops.rs:1379:51
     |
1379 |         let path_res = cx.tables.qpath_def(qpath, expr.id);
     |                                                   ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
     |
     = note: expected type `rustc::hir::HirId`
                found type `syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/mem_forget.rs:35:57
   |
35 |                 let def_id = cx.tables.qpath_def(qpath, path_expr.id).def_id();
   |                                                         ^^^^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/methods.rs:901:58
    |
901 |         let Def::Method(did) = cx.tables.qpath_def(path, fun.id),
    |                                                          ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/minmax.rs:65:53
   |
65 |             let def_id = cx.tables.qpath_def(qpath, path.id).def_id();
   |                                                     ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/misc.rs:364:69
    |
364 |                     non_macro_local(cx, &cx.tables.qpath_def(qpath, expr.id))
    |                                                                     ^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0616]: field `type_dependent_defs` of struct `rustc::ty::TypeckTables` is private
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/mut_reference.rs:50:30
   |
50 |                 let def_id = cx.tables.type_dependent_defs[&e.id].def_id();
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: a method `type_dependent_defs` also exists, perhaps you wish to call it

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/mut_reference.rs:50:60
   |
50 |                 let def_id = cx.tables.type_dependent_defs[&e.id].def_id();
   |                                                            ^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `&rustc::hir::ItemLocalId`
              found type `&syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/mut_reference.rs:51:52
   |
51 |                 let substs = cx.tables.node_substs(e.id);
   |                                                    ^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/no_effect.rs:72:54
   |
72 |                 let def = cx.tables.qpath_def(qpath, callee.id);
   |                                                      ^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/no_effect.rs:168:54
    |
168 |                 let def = cx.tables.qpath_def(qpath, callee.id);
    |                                                      ^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/print.rs:128:61
    |
128 |                     let def_id = cx.tables.qpath_def(qpath, args[1].id).def_id();
    |                                                             ^^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/regex.rs:121:53
    |
121 |             let def_id = cx.tables.qpath_def(qpath, fun.id).def_id();
    |                                                     ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/shadow.rs:152:44
    |
152 |     let var_ty = cx.tables.node_id_to_type(pat_id);
    |                                            ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/transmute.rs:91:57
   |
91 |                 let def_id = cx.tables.qpath_def(qpath, path_expr.id).def_id();
   |                                                         ^^^^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
   |
   = note: expected type `rustc::hir::HirId`
              found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/types.rs:152:50
    |
152 |             let def = cx.tables.qpath_def(qpath, ast_ty.id);
    |                                                  ^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/types.rs:160:79
    |
160 |                         let def::Def::Struct(..) = cx.tables.qpath_def(qpath, vec.id),
    |                                                                               ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/types.rs:161:79
    |
161 |                         let Some(did) = opt_def_id(cx.tables.qpath_def(qpath, vec.id)),
    |                                                                               ^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.151/src/types.rs:205:58
    |
205 |                     let def = cx.tables.qpath_def(qpath, ast_ty.id);
    |                                                          ^^^^^^^^^ expected struct `rustc::hir::HirId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::HirId`
               found type `syntax::ast::NodeId`

error: aborting due to 53 previous errors

error: Could not compile `clippy_lints`.
```

**Comment by oli-obk** [comment]
fixed in 0.0.152
