### ISSUE TITLE
Does not compile on rustc 1.25.0-nightly (6828cf901 2018-01-06)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2333]
Lots of errors like this:

```
error[E0599]: no variant named `Us` found for type `syntax::ast::UintTy` in the current scope
  --> clippy_lints-0.0.177/src/mutex_atomic.rs:72:47
   |
72 |                         ty::TyUint(t) if t != ast::UintTy::Us => span_lint(cx, MUTEX_INTEGER, expr.span, &msg),
   |                                               ^^^^^^^^^^^^^^^ variant not found in `syntax::ast::UintTy`
```

**Comment by Arnavion** [comment]
https://github.com/rust-lang/rust/commit/210ac01792878ce0d654e852b0c794c782c04e01

**Comment by Arnavion** [comment]
Fixed in v0.0.178

**Comment by dtolnay** [comment]
Confirmed fixed. Thanks!
