### ISSUE TITLE
Does not compile on rustc 1.25.0-nightly (61452e506 2018-01-09)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2341]
```
error[E0599]: no method named `struct_variant` found for type `&rustc::ty::AdtDef` in the current scope
  --> clippy_lints-0.0.178/src/needless_update.rs:38:40
   |
38 |                 if fields.len() == def.struct_variant().fields.len() {
   |                                        ^^^^^^^^^^^^^^
```

**Comment by sum01** [comment]
I ran into this as well, but v0.0.179 seems to have fixed this issue.

**Comment by dtolnay** [comment]
Indeed. Thanks!
