### ISSUE TITLE
Can't find crate for pulldown_cmark

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#1906]
#### rustc 1.21.0-nightly (52a330969 2017-07-27)

```
   Compiling clippy_lints v0.0.145
error[E0463]: can't find crate for `pulldown_cmark`
  --> clippy_lints/src/lib.rs:55:1
   |
55 | extern crate pulldown_cmark;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by dtolnay** [comment]
It compiles fine with rustc 1.21.0-nightly (599be0d18 2017-07-26).

**Comment by oli-obk** [comment]
fixed in 0.0.146

**Comment by llogiq** [comment]
@oli-obk Did you forget to push? Our current master still says 0.0.145.

**Comment by oli-obk** [comment]
I did. sorry. Will push sunday evening

**Comment by xftroxgpx** [comment]
> I did. sorry. Will push sunday evening

What? No! I need this [today](https://travis-ci.org/xftroxgpx/rustlearnage/jobs/258953072#L1117)! Er.. I mean, whenever you can :))
Cheers

**Comment by llogiq** [comment]
This just means that clippy devs have to put a`pulldown-cmark = "0.1.15" ` in the clippy_lints' dependecies until @oli-obk pushes.

**Comment by oli-obk** [comment]
Yea. The PC with the relevant commits has quite some physical distance to me and is not turned on and does not allow wake-on-lan

**Comment by kraai** [comment]
@llogiq I think you have the version number of pulldown-cmark wrong: I had to use 0.0.15 instead of 0.1.15.

**Comment by xftroxgpx** [comment]
Makes sense: https://github.com/google/pulldown-cmark/blob/master/Cargo.toml#L3

**Comment by oli-obk** [comment]
It has been pushed, updating for nightly now ^^
