### PR TITLE
Try to fix #1928

### LINKED ISSUE #1928: Failed to build with rustc 1.21.0-nightly (ed16b0a1d 2017-08-05)
Due to: rust-lang/rust#43554
Logs:
```
error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:407:19
    |
407 |             val @ ConstFloat::F32(_) => {
    |                   ^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:417:19
    |
417 |             val @ ConstFloat::F64(_) => {
    |                   ^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:408:28
    |
408 |                 let zero = ConstFloat::F32(0.0);
    |                            ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:410:32
    |
410 |                 let infinity = ConstFloat::F32(::std::f32::INFINITY);
    |                                ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:412:36
    |
412 |                 let neg_infinity = ConstFloat::F32(::std::f32::NEG_INFINITY);
    |                                    ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:418:28
    |
418 |                 let zero = ConstFloat::F64(0.0);
    |                            ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:420:32
    |
420 |                 let infinity = ConstFloat::F64(::std::f64::INFINITY);
    |                                ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:422:36
    |
422 |                 let neg_infinity = ConstFloat::F64(::std::f64::NEG_INFINITY);
    |                                    ^^^^^^^^^^^^^^^

error: aborting due to 8 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.148`, intermediate artifacts can be found at `/tmp/cargo-install.qq9jCb3lqqwF`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by Frederick888**
Hope this is the correct way to fix it as I have completely no ideas about the floating points.

Fixes #1928

### CODE REVIEW

**Comment by llogiq** [comment]
Thank you!

**Comment by llogiq** [comment]
This broke dogfood. I've fixed it on master. Strange that CI did not catch it. No worries, just wanted to let you know that a little `cargo test` before pushing that PR can work wonders :wink:

**Comment by Frederick888** [comment]
@llogiq Ah, sorry. I though I only needed to run `cargo test examples`. I remember that there is a list of todos before PR somewhere but I cannot find it now. Do you know where it is?

**Comment by oli-obk** [comment]
We have https://github.com/rust-lang-nursery/rust-clippy/blob/master/CONTRIBUTING.md but it should probably also state that `cargo test` should be run ^^

**Comment by llogiq** [comment]
As I said, no worries, I caught it quickly, and I haven't made a release yet  anyway (CI is still acting up, and I have to fix lunch for my family). @oli-obk can you take it from here? I won't have much time during the next hours.

**Comment by oli-obk** [comment]
Oh that was me. I changed Travis rules so we wouldn't build both the branch and the PR, but still built the master branch once a day. I changed it back so branches are built again

**Comment by Thomasdezeeuw** [comment]
Any chance this would get a update on crates.io? Clippy is currently broken for me (v0.0.148) and this seems to fix it.

**Comment by oli-obk** [comment]
I won't get to it today, but it'll be the first thing I'll do on monday

**Comment by llogiq** [comment]
I just published.

**Comment by llogiq** [comment]
I could however not add the 0.0.149 tag due to my GPG key not yet being on this system. :slightly_frowning_face: Ah, well, I'll leave it to @oli-obk to add the tag tomorrow.

**Comment by oli-obk** [comment]
done

**Comment by llogiq** [comment]
Thank you!

**Comment by Thomasdezeeuw** [comment]
Everything works again, thanks!
