### ISSUE TITLE
Clippy is broken with nightly

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-clippy#2184]
```shell
   Compiling clippy_lints v0.0.166
error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
  --> /Users/gnzlbg/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/lifetimes.rs:69:58
   |
69 |             check_fn_inner(cx, &sig.decl, Some(id), &sig.generics, item.span);
   |                                                          ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
  --> /Users/gnzlbg/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/lifetimes.rs:79:54
   |
79 |             check_fn_inner(cx, &sig.decl, body, &sig.generics, item.span);
   |                                                      ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
   --> /Users/gnzlbg/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/methods.rs:722:84
    |
722 |                    self_kind.matches(first_arg_ty, first_arg, self_ty, false, &sig.generics) {
    |                                                                                    ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
   --> /Users/gnzlbg/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/methods.rs:736:106
    |
736 |                     !self_kinds.iter().any(|k| k.matches(first_arg_ty, first_arg, self_ty, is_copy, &sig.generics)),
    |                                                                                                          ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
   --> /Users/gnzlbg/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/new_without_default.rs:111:21
    |
111 |             if !sig.generics.ty_params.is_empty() {
    |                     ^^^^^^^^

error: aborting due to 5 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.166`, intermediate artifacts can be found at `/var/folders/mm/y444qqwd0kn52fycyz6nsph40000gn/T/cargo-install.nt8TXBcHowWR`

Caused by:
  build failed
```

**Comment by marcaddeo** [comment]
I got it working by downgrading to `nightly-2017-10-24`

```bash
rustup toolchain install nightly-2017-10-24
rustup default nightly-2017-10-24
```

**Comment by hcpl** [comment]
Caused by https://github.com/rust-lang/rust/pull/44766.
