### PR TITLE
Fixes #2239

### LINKED ISSUE #2239: Failed to build with rustc 1.23.0-nightly (33374fa9d 2017-11-20)
Due to: rust-lang/rust#45225

Log:
```
error[E0599]: no method named `layout` found for type `&'tcx rustc::ty::TyS<'tcx>` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.172/src/utils/mod.rs:1024:8
     |
1024 |     ty.layout(cx.tcx, cx.param_env)
     |        ^^^^^^

error: aborting due to previous error

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.172`, intermediate artifacts can be found at `/tmp/cargo-install.q3IwltO2ONEC`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by Frederick888**
Fixes #2239. Minor changes only.

### CODE REVIEW

**Comment by oli-obk** [comment]
Thanks! I'll publish right away
