### ISSUE TITLE
Clippy 0.0.160 fails to build on 1.22.0-nightly (539f2083d 2017-09-13)

### ISSUE THREAD

**Issue by gyscos** [rust-lang-nursery/rust-clippy#2050]
```
   Compiling clippy v0.0.160
error[E0050]: method `late_callback` has 6 parameters but the declaration in trait `rustc_driver::CompilerCalls::late_callback` has 7
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy-0.0.160/src/main.rs:69:16
   |
69 |         ofile: &Option<PathBuf>,
   |                ^^^^^^^^^^^^^^^^ expected 7 parameters, found 6
   |
   = note: `late_callback` from trait: `fn(&mut Self, &getopts::Matches, &rustc::session::Session, &rustc::middle::cstore::CrateStore, &rustc::session::config::Input, &std::option::Option<std::path::PathBuf>, &std::option::Option<std::path::PathBuf>) -> rustc_driver::Compilation`

error: aborting due to previous error

error: failed to compile `clippy v0.0.160`, intermediate artifacts can be found at `/tmp/cargo-install.adUjjCymM7ur`

Caused by:
  Could not compile `clippy`.

To learn more, run the command again with --verbose.
```

Seems to come from https://github.com/rust-lang/rust/pull/44420.

**Comment by oli-obk** [comment]
Published as 0.0.161
