### PR TITLE
Try to fix #1914

### LINKED ISSUE #1914: Failed to build with rustc 1.21.0-nightly (37c7d0ebb 2017-07-31)
Due to: rust-lang/rust#43399

Logs:
```
error[E0432]: unresolved import `rustc::hir::BindingMode`                                                                                                                                      
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/needless_borrow.rs:6:64                                                                                          
  |                                                                                                                                                                                            
6 | use rustc::hir::{ExprAddrOf, Expr, MutImmutable, Pat, PatKind, BindingMode};                                                                                                               
  |                                                                ^^^^^^^^^^^ no `BindingMode` in `hir`                                                                                       
                                                                                                                                                                                               
error[E0432]: unresolved import `rustc::hir::BindingMode`                                                                                                                                      
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/needless_borrowed_ref.rs:6:46                                                                                    
  |                                                                                                                                                                                            
6 | use rustc::hir::{MutImmutable, Pat, PatKind, BindingMode};                                                                                                                                 
  |                                              ^^^^^^^^^^^ no `BindingMode` in `hir`                                                                                                         
                                                                                                                                                                                               
error[E0531]: cannot find tuple struct/variant `BindByRef` in module `hir`                                                                                                                     
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/let_if_seq.rs:97:26                                                                                             
   |                                                                                                                                                                                           
97 |                     hir::BindByRef(hir::MutMutable) | hir::BindByValue(hir::MutMutable) => "<mut> ",                                                                                      
   |                          ^^^^^^^^^ not found in `hir`                                                                                                                                     
                                                                                                                                                                                               
error[E0531]: cannot find tuple struct/variant `BindByValue` in module `hir`                                                                                                                   
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/let_if_seq.rs:97:60                                                                                             
   |                                                                                                                                                                                           
97 |                     hir::BindByRef(hir::MutMutable) | hir::BindByValue(hir::MutMutable) => "<mut> ",
   |                                                            ^^^^^^^^^^^ not found in `hir`
   |
help: possible candidates are found in other modules, you can import them into scope
   |
62 |         if let $pat = $expr use rustc::ty::BindByValue;
   |
62 |         if let $pat = $expr use rustc::ty::BindingMode::BindByValue;
   |

error[E0531]: cannot find tuple struct/variant `BindByValue` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/matches.rs:246:26
    |
246 |         PatKind::Binding(BindByValue(MutImmutable), _, ident, None) => ident.node.to_string(),
    |                          ^^^^^^^^^^^ not found in this scope
    |
help: possible candidates are found in other modules, you can import them into scope
    |
106 | use rustc::ty::BindByValue;
    |
106 | use rustc::ty::BindingMode::BindByValue;
    |

error[E0531]: cannot find tuple struct/variant `BindByRef` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/misc.rs:228:37
    |
228 |             if let PatKind::Binding(BindByRef(_), _, _, _) = arg.pat.node {
    |                                     ^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `BindByRef` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/misc.rs:241:34
    |
241 |             let PatKind::Binding(BindByRef(mt), _, i, None) = l.pat.node,
    |                                  ^^^^^^^^^ not found in this scope

error[E0433]: failed to resolve. Use of undeclared type or module `BindingMode`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/needless_pass_by_value.rs:127:21
    |
127 |                     BindingMode::BindByRef(m) | BindingMode::BindByValue(m) => m,
    |                     ^^^^^^^^^^^ Use of undeclared type or module `BindingMode`

error[E0433]: failed to resolve. Use of undeclared type or module `BindingMode`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.147/src/needless_pass_by_value.rs:127:49
    |
127 |                     BindingMode::BindByRef(m) | BindingMode::BindByValue(m) => m,
    |                                                 ^^^^^^^^^^^ Use of undeclared type or module `BindingMode`

error: aborting due to 9 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.147`, intermediate artifacts can be found at `/tmp/cargo-install.uOP6JKz7S4Xq`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by Frederick888**
First time PR to this repo, careful check needed. Thanks.

Fixes #1914

### CODE REVIEW

**Comment by oli-obk** [comment]
Awesome thanks! I'll publish immediately.
