### ISSUE TITLE
Does not compile on rustc 1.28.0-nightly (cbc4c8380 2018-06-22)

### ISSUE THREAD

**Issue by jebrosen** [rust-lang-nursery/rust-clippy#2869]
rust-lang/rust#48149 looks like the most likely culprit.

<details>
<summary>40 errors</summary>

```
error[E0433]: failed to resolve. Could not find `TyParamBound` in `hir`
    --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/methods.rs:2096:29
     |
2096 |                 if let hir::TyParamBound::TraitTyParamBound(ref ptr, ..) = *bound {
     |                             ^^^^^^^^^^^^ Could not find `TyParamBound` in `hir`

error[E0412]: cannot find type `PathParameters` in this scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/utils/hir_utils.rs:204:45
    |
204 |     fn eq_path_parameters(&mut self, left: &PathParameters, right: &PathParameters) -> bool {
    |                                             ^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `PathParameters` in this scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/utils/hir_utils.rs:204:69
    |
204 |     fn eq_path_parameters(&mut self, left: &PathParameters, right: &PathParameters) -> bool {
    |                                                                     ^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `TraitTyParamBound` in this scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:106:20
    |
106 |             if let TraitTyParamBound(ref trait_ref, _) = *bound {
    |                    ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `RegionTyParamBound` in this scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:333:32
    |
333 |                         if let RegionTyParamBound(_) = *bound {
    |                                ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `walk_ty_param_bound` in this scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:375:21
    |
375 |                     walk_ty_param_bound(&mut visitor, bound);
    |                     ^^^^^^^^^^^^^^^^^^^ did you mean `walk_param_bound`?

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/utils/hir_utils.rs:227:22
    |
227 |         match (&left.parameters, &right.parameters) {
    |                      ^^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/utils/hir_utils.rs:227:41
    |
227 |         match (&left.parameters, &right.parameters) {
    |                                         ^^^^^^^^^^

error[E0599]: no method named `ty_params` found for type `&'tcx rustc::hir::Generics` in the current scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:104:25
    |
104 |     for typ in generics.ty_params() {
    |                         ^^^^^^^^^

error[E0609]: no field `lifetimes` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:115:42
    |
115 |                     for bound in &params.lifetimes {
    |                                          ^^^^^^^^^

error[E0599]: no associated item named `Lifetime` found for type `rustc::hir::GenericParam` in the current scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:228:16
    |
228 |         if let GenericParam::Lifetime(ref lt) = *par {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ associated item not found in `rustc::hir::GenericParam`

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:293:71
    |
293 |         if let Some(ref last_path_segment) = last_path_segment(qpath).parameters {
    |                                                                       ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:294:35
    |
294 |             if !last_path_segment.parenthesized && last_path_segment.lifetimes.is_empty() {
    |                                   ^^^^^^^^^^^^^

error[E0599]: no method named `is_type_param` found for type `&'tcx rustc::hir::GenericParam` in the current scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:416:18
    |
416 |         if param.is_type_param() {
    |                  ^^^^^^^^^^^^^

error[E0599]: no method named `lifetimes` found for type `&'tcx rustc::hir::Generics` in the current scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/lifetimes.rs:427:10
    |
427 |         .lifetimes()
    |          ^^^^^^^^^

error[E0560]: struct `rustc::hir::PathSegment` has no field named `parameters`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/map_clone.rs:106:21
    |
106 |                     parameters: None,
    |                     ^^^^^^^^^^ `rustc::hir::PathSegment` does not have this field
    |
    = note: available fields are: `name`, `args`, `infer_types`

error[E0599]: no method named `ty_params` found for type `&rustc::hir::Generics` in the current scope
    --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/methods.rs:2094:18
     |
2094 |         generics.ty_params().any(|param| {
     |                  ^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
    --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/methods.rs:2099:53
     |
2099 |                         if let Some(ref params) = s.parameters {
     |                                                     ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
    --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/methods.rs:2100:39
     |
2100 |                             if params.parenthesized {
     |                                       ^^^^^^^^^^^^^

error[E0599]: no associated item named `Type` found for type `syntax::ast::GenericParam` in the current scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/misc_early.rs:192:20
    |
192 |             if let GenericParam::Type(ref ty) = *param {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ associated item not found in `syntax::ast::GenericParam`

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/needless_pass_by_value.rs:221:51
    |
221 |                                 .and_then(|ps| ps.parameters.as_ref())
    |                                                   ^^^^^^^^^^

error[E0599]: no method named `is_type_param` found for type `&rustc::hir::GenericParam` in the current scope
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/new_without_default.rs:106:75
    |
106 |                         if impl_item.generics.params.iter().any(|gen| gen.is_type_param()) {
    |                                                                           ^^^^^^^^^^^^^

error[E0026]: struct `rustc::hir::PathSegment` does not have a field named `parameters`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/ptr.rs:163:46
    |
163 |                     if let Some(&PathSegment{parameters: Some(ref parameters), ..}) = path.segments.last();
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ struct `rustc::hir::PathSegment` does not have this field

error[E0609]: no field `types` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/ptr.rs:164:35
    |
164 |                     if parameters.types.len() == 1;
    |                                   ^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/ptr.rs:221:50
    |
221 |                     if let Some(ref params) = bx.parameters;
    |                                                  ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/ptr.rs:222:32
    |
222 |                     if !params.parenthesized;
    |                                ^^^^^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/transmute.rs:458:39
    |
458 |         if let Some(ref params) = seg.parameters;
    |                                       ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/transmute.rs:459:20
    |
459 |         if !params.parenthesized;
    |                    ^^^^^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:183:40
    |
183 |         if let Some(ref params) = last.parameters;
    |                                        ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:184:20
    |
184 |         if !params.parenthesized;
    |                    ^^^^^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:247:29
    |
247 |                         seg.parameters
    |                             ^^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:255:25
    |
255 |                     seg.parameters
    |                         ^^^^^^^^^^

error[E0609]: no field `parameters` on type `&syntax::ptr::P<rustc::hir::PathSegment>`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:263:51
    |
263 |                     if let Some(ref params) = seg.parameters {
    |                                                   ^^^^^^^^^^

error[E0609]: no field `types` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:264:42
    |
264 |                         for ty in params.types.iter() {
    |                                          ^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:291:46
    |
291 |                 if let Some(ref params) = bx.parameters;
    |                                              ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
   --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:292:28
    |
292 |                 if !params.parenthesized;
    |                            ^^^^^^^^^^^^^

error[E0599]: no method named `is_lifetime_param` found for type `&rustc::hir::GenericParam` in the current scope
    --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:1211:82
     |
1211 |                     .any(|bound| bound.bound_generic_params.iter().any(|gen| gen.is_lifetime_param()));
     |                                                                                  ^^^^^^^^^^^^^^^^^

error[E0609]: no field `parameters` on type `&&rustc::hir::PathSegment`
    --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/types.rs:1862:58
     |
1862 |             let params = &path.segments.last().as_ref()?.parameters.as_ref()?.types;
     |                                                          ^^^^^^^^^^

error[E0609]: no field `parameters` on type `&rustc::hir::PathSegment`
  --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/use_self.rs:61:82
   |
61 |                 let parameters = &item_path.segments.last().expect(SEGMENTS_MSG).parameters;
   |                                                                                  ^^^^^^^^^^

error[E0609]: no field `parenthesized` on type `&_`
  --> /home/mee/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.209/src/use_self.rs:63:29
   |
63 |                     !params.parenthesized && params.lifetimes.len() == 0
   |                             ^^^^^^^^^^^^^

error: aborting due to 40 previous errors
```

</details>

**Comment by mikerite** [comment]
That is probably going to take a while to fix.

`rustup install nightly-2018-06-19` seems to work if you need clippy in the meantime.

**Comment by jedahan** [comment]
Maybe the readme should be updated to show this?

**Comment by flip1995** [comment]
I'm currently on this. I got it compiling again. Now I'm looking into the failing tests.

**Comment by oli-obk** [comment]
Thanks @flip1995 

Published as 0.0.210
