### PR TITLE
Try to fix #1988

### LINKED ISSUE #1988: Failed to build with rustc 1.21.0-nightly (2c0558f63 2017-08-24)
Due to: rust-lang/rust#43532

Logs:
```
error[E0531]: cannot find tuple struct/variant `AngleBracketedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:199:15
    |
199 |             (&AngleBracketedParameters(ref left), &AngleBracketedParameters(ref right)) => {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `AngleBracketedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:199:52
    |
199 |             (&AngleBracketedParameters(ref left), &AngleBracketedParameters(ref right)) => {
    |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `ParenthesizedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:204:15
    |
204 |             (&ParenthesizedParameters(ref left), &ParenthesizedParameters(ref right)) => {
    |               ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `ParenthesizedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:204:51
    |
204 |             (&ParenthesizedParameters(ref left), &ParenthesizedParameters(ref right)) => {
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `AngleBracketedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:208:15
    |
208 |             (&AngleBracketedParameters(_), &ParenthesizedParameters(_)) |
    |               ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `ParenthesizedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:208:45
    |
208 |             (&AngleBracketedParameters(_), &ParenthesizedParameters(_)) |
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `ParenthesizedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:209:15
    |
209 |             (&ParenthesizedParameters(_), &AngleBracketedParameters(_)) => false,
    |               ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `AngleBracketedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/utils/hir_utils.rs:209:44
    |
209 |             (&ParenthesizedParameters(_), &AngleBracketedParameters(_)) => false,
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0531]: cannot find tuple struct/variant `AngleBracketedParameters` in this scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/lifetimes.rs:285:16
    |
285 |         if let AngleBracketedParameters(ref params) = *last_path_segment {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `lifetimes` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/lifetimes.rs:114:22
    |
114 |                     .lifetimes();
    |                      ^^^^^^^^^ field, not a method
    |
    = help: did you mean to write `trait_ref
                                .trait_ref
                                .path
                                .segments
                                .last()
                                .expect("a path must have at least one segment")
                                .parameters.lifetimes` instead of `trait_ref
                                .trait_ref
                                .path
                                .segments
                                .last()
                                .expect("a path must have at least one segment")
                                .parameters.lifetimes(...)`?

error[E0599]: no associated item named `AngleBracketedParameters` found for type `rustc::hir::PathParameters` in the current scope
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/methods.rs:1467:40
     |
1467 |                                 if let hir::PathParameters::AngleBracketedParameters(ref data) = s.parameters {
     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `types` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/needless_pass_by_value.rs:150:53
    |
150 |                             .map(|ps| ps.parameters.types()[0]),
    |                                                     ^^^^^ field, not a method
    |
    = help: did you mean to write `ps.parameters.types` instead of `ps.parameters.types(...)`?

error[E0599]: no associated item named `AngleBracketedParameters` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/transmute.rs:211:13
    |
211 |         let PathParameters::AngleBracketedParameters(ref ang) = seg.parameters,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `AngleBracketedParameters` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/types.rs:158:29
    |
158 |                         let PathParameters::AngleBracketedParameters(ref ag) = last.parameters,
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `types` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/types.rs:185:79
    |
185 |                     for ty in p.segments.iter().flat_map(|seg| seg.parameters.types()) {
    |                                                                               ^^^^^ field, not a method
    |
    = help: did you mean to write `seg.parameters.types` instead of `seg.parameters.types(...)`?

error[E0599]: no method named `types` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/types.rs:190:79
    |
190 |                     for ty in p.segments.iter().flat_map(|seg| seg.parameters.types()) {
    |                                                                               ^^^^^ field, not a method
    |
    = help: did you mean to write `seg.parameters.types` instead of `seg.parameters.types(...)`?

error[E0599]: no method named `types` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/types.rs:196:46
    |
196 |                     for ty in seg.parameters.types() {
    |                                              ^^^^^ field, not a method
    |
    = help: did you mean to write `seg.parameters.types` instead of `seg.parameters.types(...)`?

error[E0599]: no associated item named `AngleBracketedParameters` found for type `rustc::hir::PathParameters` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.153/src/types.rs:212:29
    |
212 |                         let PathParameters::AngleBracketedParameters(ref ab_data) = bx.parameters,
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 18 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.153`, intermediate artifacts can be found at `/tmp/cargo-install.znCns9HVD6Ev`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by Frederick888**
Fixes #1988

### CODE REVIEW

**Comment by mcarton** [comment]
Thanks!
