### PR TITLE
Try to fix #1941

### LINKED ISSUE #1941: Failed to build with rustc 1.21.0-nightly (215e0b10e 2017-08-08)
Due to: rust-lang/rust@453ad8122c975dc82f6090f0c755d38932ccefc5
Logs:
```
error[E0599]: no method named `for_each_relevant_impl` found for type `&rustc::ty::TraitDef` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.149/src/derive.rs:101:23
    |
101 |         peq_trait_def.for_each_relevant_impl(cx.tcx, ty, |impl_id| {
    |                       ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.149`, intermediate artifacts can be found at `/tmp/cargo-install.hM50konMQ6a3`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by Frederick888**
Just a minor change. `cargo test` passed.

Fixes #1941

### CODE REVIEW

**Comment by llogiq** [comment]
Thanks! Alas, I need to catch my train, so someone else please publish @Manishearth @oli-obk @mcarton

**Comment by oli-obk** [comment]
done
