### ISSUE TITLE
clippy_lints doesn't build on rust 1.21.0-nightly (13d94d5fa 2017-08-10)

### ISSUE THREAD

**Issue by Biohazard50** [rust-lang-nursery/rust-clippy#1946]
Full log [here](https://pastebin.com/nHRnB9zD).
All the errors say that the method `current_level` cannot be found.

**Comment by atorstling** [comment]
Found the commit removing the method: https://github.com/rust-lang/rust/commit/2400ebfe76225745d1591c8a63c54570174ab22c

**Comment by xftroxgpx** [comment]
to make search easier:
```
error[E0599]: no method named `current_level` found for type `&'a T` in the current scope
```

**Comment by shssoichiro** [comment]
Looks like there's been some more breakage between 8-10 and 8-13 as well, on top of this.

**Comment by shssoichiro** [comment]
I've pushed to a forked branch `1946-Nightly-Breakage`, clippy compiles but has failing tests at this point. I'll work on it some more tomorrow if no one has taken a look by then.

**Comment by oli-obk** [comment]
@shssoichiro sorry, I forgot to push and wasn't able to publish yesterday. New version should be up in a minute.

**Comment by oli-obk** [comment]
`0.0.151` is live!
