### ISSUE TITLE
Does not compile on 1.22.0-nightly (f861b6ee4 2017-09-01)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2013]
```
error[E0308]: mismatched types
   --> clippy_lints/src/loops.rs:625:60
    |
625 |                     let pat_extent = region_maps.var_scope(pat.id);
    |                                                            ^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::ItemLocalId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
    --> clippy_lints/src/loops.rs:1070:83
     |
1070 |                     let extent = self.cx.tcx.region_maps(parent_def_id).var_scope(node_id);
     |                                                                                   ^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
     |
     = note: expected type `rustc::hir::ItemLocalId`
                found type `syntax::ast::NodeId`
```

**Comment by montrivo** [comment]
Can you not use the `hir_id` field of the `Pat` struct?
