### ISSUE TITLE
Failed to build with rustc 1.21.0-nightly (ed16b0a1d 2017-08-05)

### ISSUE THREAD

**Issue by Frederick888** [rust-lang-nursery/rust-clippy#1928]
Due to: rust-lang/rust#43554
Logs:
```
error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:407:19
    |
407 |             val @ ConstFloat::F32(_) => {
    |                   ^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:417:19
    |
417 |             val @ ConstFloat::F64(_) => {
    |                   ^^^^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:408:28
    |
408 |                 let zero = ConstFloat::F32(0.0);
    |                            ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:410:32
    |
410 |                 let infinity = ConstFloat::F32(::std::f32::INFINITY);
    |                                ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F32` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:412:36
    |
412 |                 let neg_infinity = ConstFloat::F32(::std::f32::NEG_INFINITY);
    |                                    ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:418:28
    |
418 |                 let zero = ConstFloat::F64(0.0);
    |                            ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:420:32
    |
420 |                 let infinity = ConstFloat::F64(::std::f64::INFINITY);
    |                                ^^^^^^^^^^^^^^^

error[E0599]: no associated item named `F64` found for type `rustc_const_math::ConstFloat` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.148/src/misc.rs:422:36
    |
422 |                 let neg_infinity = ConstFloat::F64(::std::f64::NEG_INFINITY);
    |                                    ^^^^^^^^^^^^^^^

error: aborting due to 8 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.148`, intermediate artifacts can be found at `/tmp/cargo-install.qq9jCb3lqqwF`

Caused by:
  build failed
```
