### PR TITLE
 Use rustc::hir::ItemLocalId instead of syntax::ast::NodeId 

### LINKED ISSUE #2013: Does not compile on 1.22.0-nightly (f861b6ee4 2017-09-01)
```
error[E0308]: mismatched types
   --> clippy_lints/src/loops.rs:625:60
    |
625 |                     let pat_extent = region_maps.var_scope(pat.id);
    |                                                            ^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
    |
    = note: expected type `rustc::hir::ItemLocalId`
               found type `syntax::ast::NodeId`

error[E0308]: mismatched types
    --> clippy_lints/src/loops.rs:1070:83
     |
1070 |                     let extent = self.cx.tcx.region_maps(parent_def_id).var_scope(node_id);
     |                                                                                   ^^^^^^^ expected struct `rustc::hir::ItemLocalId`, found struct `syntax::ast::NodeId`
     |
     = note: expected type `rustc::hir::ItemLocalId`
                found type `syntax::ast::NodeId`
```

### PR DESCRIPTION
**Pull request by topecongiro**
Closes #2013.

### CODE REVIEW

**Comment by montrivo** [comment]
Can you not use the  `hir_id` of the `Pat` struct?

**Comment by Arnavion** [comment]
Already fixed by 4807909152d64827363c712242ef6831b32533c9

**Comment by topecongiro** [comment]
@montrivo @Arnavion Thanks!
