### ISSUE TITLE
Clippy not working with latest nightly: 1.27.0-nightly (7f3444e1b 2018-04-26)

### ISSUE THREAD

**Issue by phansch** [rust-lang-nursery/rust-clippy#2698]
Various failures:

```
Compiling unreachable v1.0.0                                                                                                                                              
error[E0658]: procedural macros cannot be expanded to expressions                                                                                                            
  --> mini-macro/src/lib.rs:8:5                                                                                                                                              
   |                                                                                                                                                                         
8  | /     quote!(                                                                                                                                                           
9  | |         #[allow(unused)] fn needless_take_by_value(s: String) { println!("{}", s.len()); }                                                                            
10 | |     )                                                                                                                                                                 
   | |_____^                                                                                                                                                                 
   |                                                                                                                                                                         
   = help: add #![feature(proc_macro_non_items)] to the crate attributes to enable
```

Also here: https://travis-ci.org/rust-lang-nursery/rust-clippy/builds/371894001#L591-L623

**Comment by mati865** [comment]
I think I'll be able to solve it.
