### PR TITLE
Fix compilation errors with rustc 1.23.0-nightly (d762b1d6c 2017-11-04)

### LINKED ISSUE #2204: Cannot compile Clippy on rustc 1.23.0-nightly (d762b1d6c 2017-11-04)
`clippy` does not compile on the current nightly, rustc 1.23.0-nightly (d762b1d6c 2017-11-04)

I see the following errors:

```

error[E0531]: cannot find tuple struct/variant `ItemDefaultImpl` in module `hir`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.168/src/utils/inspector.rs:406:14
    |
406 |         hir::ItemDefaultImpl(_, ref _trait_ref) => {
    |              ^^^^^^^^^^^^^^^ not found in `hir`

error[E0531]: cannot find tuple struct/variant `ItemDefaultImpl` in module `hir`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.168/src/functions.rs:89:81
   |
89 |             matches!(item.node, hir::ItemImpl(_, _, _, _, Some(_), _, _) | hir::ItemDefaultImpl(..))
   |                                                                                 ^^^^^^^^^^^^^^^ not found in `hir`

error[E0531]: cannot find tuple struct/variant `ItemDefaultImpl` in module `hir`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.168/src/missing_doc.rs:135:18
    |
135 |             hir::ItemDefaultImpl(..) |
    |                  ^^^^^^^^^^^^^^^ not found in `hir`

error[E0599]: no method named `trait_has_default_impl` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.168/src/utils/inspector.rs:400:23
    |
400 |             if cx.tcx.trait_has_default_impl(did) {
    |                       ^^^^^^^^^^^^^^^^^^^^^^

error[E0023]: this pattern has 4 fields, but the corresponding tuple variant has 5 fields
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.168/src/len_zero.rs:71:13
   |
71 |             ItemTrait(_, _, _, ref trait_items) => check_trait_items(cx, item, trait_items),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 fields, found 4

error: aborting due to 5 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.168`, intermediate artifacts can be found at `/tmp/cargo-install.tXHpQc2gbFKg`

Caused by:
  build failed

```

### PR DESCRIPTION
**Pull request by kraai**
Fixes #2204

### CODE REVIEW

**Comment by oli-obk** [comment]
Awesome thanks!
