### PR TITLE
Try to fix #1970

### LINKED ISSUE #1970: Failed to build with rustc 1.21.0-nightly (230a379a4 2017-08-18)
Due to: rust-lang/rust#43832

Logs:

```
error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.152/src/utils/mod.rs:117:61
    |
117 |             ExpnFormat::CompilerDesugaring(name) => name != "...",
    |                                                             ^^^^^ expected enum `syntax_pos::CompilerDesugaringKind`, found reference
    |
    = note: expected type `syntax_pos::CompilerDesugaringKind`
               found type `&'static str`

error: aborting due to previous error

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.152`, intermediate artifacts can be found at `/tmp/cargo-install.zAvvHQr48G8S`

Caused by:
  build failed
```

### PR DESCRIPTION
**Pull request by Frederick888**
Fixes #1970

### CODE REVIEW

**Comment by oli-obk** [comment]
Thanks! I'll publish asap
